define([], {
    THING : "owl:Thing",
    TIMELINE : "sss:Timeline",
    ORGANIZE : "sss:Organize",
    USEREVENT : "sss:userEvent",
    EPISODE: "sss:learnEp",
    VERSION: "sss:learnEpVersion",
    USER: "sss:user",
    ORGAENTITY: "sss:learnEpEntity",
    CIRCLE: "sss:learnEpCircle",
    WIDGET: "sss:Widget",
    BROWSING_WIDGET: "sss:BrowsingWidget",
    ORGANIZING_WIDGET: "sss:OrganizingWidget",
    currentVersion: 'sss:currentVersion',
    belongsToEpisode: 'sss:belongsToEpisode',
    belongsToVersion: 'sss:belongsToVersion',
    belongsToTimeline: 'sss:belongsToTimeline',
    belongsToOrganize: 'sss:belongsToOrganize',
    hasCircle: 'sss:hasCircle',
    hasEntity: 'sss:hasEntity',
    hasVersion: 'sss:hasVersion',
    hasWidget: 'sss:hasWidget',
    hasResource : 'sss:resource',
    hasEpisode : 'sss:hasEpisode',
    timestamp : 'sss:timestamp',
    circleType: 'sss:circleType', 
    orgaEntityType: 'sss:orgaEntityType',
    belongsToUser: 'sss:belongsToUser',
    start: 'sss:start',
    end: 'sss:end',

    label : 'sss:label',
    content : 'sss:content'
});
