define([], {
    THING : "owl:Thing",
    TIMELINE : "sss:Timeline",
    ORGANIZE : "sss:Organize",
    USEREVENT : "sss:userEvent",
    EPISODE: "sss:learnEp",
    VERSION: "sss:learnEpVersion",
    USER: "sss:user",
    ORGAENTITY: "sss:learnEpEntity",
    ENTITY: "sss:entity",
    FILE: "sss:file",
    EVERNOTE_RESOURCE: "sss:evernoteResource",
    EVERNOTE_NOTE: "sss:evernoteNote",
    EVERNOTE_NOTEBOOK: "sss:evernoteNotebook",
    MESSAGE: "sss:message",
    ACTIVITY: "sss:activity",
    CIRCLE: "sss:learnEpCircle",
    WIDGET: "sss:Widget",
    BROWSING_WIDGET: "sss:BrowsingWidget",
    ORGANIZING_WIDGET: "sss:OrganizingWidget",
    currentVersion: 'sss:currentVersion',
    belongsToEpisode: 'sss:learnEp',
    belongsToVersion: 'sss:learnEpVersion',
    belongsToTimeline: 'sss:belongsToTimeline',
    belongsToOrganize: 'sss:belongsToOrganize',
    hasCircle: 'sss:learnEpCircles',
    hasEntity: 'sss:learnEpEntities',
    hasVersion: 'sss:hasVersion',
    hasWidget: 'sss:hasWidget',
    hasResource : 'sss:entity',
    hasEpisode : 'sss:hasEpisode',
    hasEntities : 'sss:entities',
    hasActivityType : 'sss:activityType',
    hasUsers : 'sss:users',
    timestamp : 'sss:timestamp',
    creationTime : 'sss:creationTime',
    timeAttr : 'sss:timeAttr',
    circleType: 'sss:circleType', 
    orgaEntityType: 'sss:orgaEntityType',
    belongsToUser: 'sss:user',
    start: 'sss:startTime',
    end: 'sss:endTime',

    label : 'sss:label',
    content : 'sss:content',
    description : 'sss:description',

    xLabel : 'sss:xLabel',
    yLabel : 'sss:yLabel',
    xR : 'sss:xR',
    yR : 'sss:yR',
    xC : 'sss:xC',
    yC : 'sss:yC',
    x : 'sss:x',
    y : 'sss:y',

    predicate : 'rdfs:range',

    author: 'sss:author',
    hasTag : 'sss:tags',
    importance : 'sss:importance',
    isUsed : 'sss:isUsed',
    hasMimeType : 'sss:mimeType',
    hasThumbnail : 'sss:thumb',
    hasLoaded : 'sss:hasLoaded',
    hasViewCount : 'sss:viewEntity',
    hasTagRecommendation : 'sss:tagRecommendation',

    hasUserEvent : 'sss:hasUserEvent',
    file : 'sss:file',
    note : 'sss:note'
        
});
