define([], {
    THING : "owl:Thing",
    TIMELINE : "sss:Timeline",
    ORGANIZE : "sss:Organize",
    USEREVENT : "sss:userEvent",
    EPISODE: "sss:learnEp",
    VERSION: "sss:learnEpVersion",
    USER: "sss:user",
    ORGAENTITY: "sss:learnEpEntity",
    ENTITY: "sss:entity",
    FILE: "sss:file",
    EVERNOTE_RESOURCE: "sss:evernoteResource",
    EVERNOTE_NOTE: "sss:evernoteNote",
    EVERNOTE_NOTEBOOK: "sss:evernoteNotebook",
    CIRCLE: "sss:learnEpCircle",
    WIDGET: "sss:Widget",
    BROWSING_WIDGET: "sss:BrowsingWidget",
    ORGANIZING_WIDGET: "sss:OrganizingWidget",
    currentVersion: 'sss:currentVersion',
    belongsToEpisode: 'sss:learnEp',
    belongsToVersion: 'sss:belongsToVersion',
    belongsToTimeline: 'sss:belongsToTimeline',
    belongsToOrganize: 'sss:belongsToOrganize',
    hasCircle: 'sss:hasCircle',
    hasEntity: 'sss:hasEntity',
    hasVersion: 'sss:hasVersion',
    hasWidget: 'sss:hasWidget',
    hasResource : 'sss:entity',
    hasEpisode : 'sss:hasEpisode',
    timestamp : 'sss:timestamp',
    creationTime : 'sss:creationTime',
    timeAttr : 'sss:timeAttr',
    circleType: 'sss:circleType', 
    orgaEntityType: 'sss:orgaEntityType',
    belongsToUser: 'sss:user',
    start: 'sss:start',
    end: 'sss:end',

    label : 'sss:label',
    content : 'sss:content',
    description : 'sss:description',

    Label : 'sss:Label',
    LabelX : 'sss:LabelX',
    LabelY : 'sss:LabelY',
    rx : 'sss:rx',
    ry : 'sss:ry',
    cx : 'sss:cx',
    cy : 'sss:cy',
    x : 'sss:x',
    y : 'sss:y',

    predicate : 'rdfs:range',

    author: 'sss:author',
    hasTag : 'sss:tags',
    importance : 'sss:importance',
    isUsed : 'sss:isUsed',
    hasMimeType : 'sss:mimeType',
    hasThumbnail : 'sss:thumb',
    thumbnailLoaded : 'sss:thumbLoaded',
    hasViewCount : 'sss:viewEntity',
    hasTagRecommendation : 'sss:tagRecommendation',

    hasUserEvent : 'sss:hasUserEvent',
    file : 'sss:file'
        
});
