<style type="text/css">
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 15.0px Arial; color: #000000; -webkit-text-stroke: #000000; min-height: 17.0px}
    li.li1 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 15.0px Arial; color: #000000; -webkit-text-stroke: #000000}
    span.s1 {font-kerning: none}
    span.s2 {font-kerning: none; background-color: #ffff00}
    span.s3 {font-kerning: none; background-color: #00ffff}
    span.s4 {font-kerning: none; background-color: #00ff00}
    span.s5 {font-kerning: none; background-color: #ff0000}
    span.s6 {font: 17.0px 'Trebuchet MS'; font-kerning: none}
    span.s7 {-webkit-text-stroke: 0px #000000}
    span.s8 {text-decoration: underline ; font-kerning: none; color: #1155cc; -webkit-text-stroke: 0px #1155cc}
    ul.ul1 {list-style-type: disc}
  </style>
<h3 style="margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 15.0px Arial; color: #000000; -webkit-text-stroke: #000000"><span class="s1"><b>B</b>its &amp; Pieces (B&amp;P, Fig. 1) can be understood as a safe place storing all your gathered informal learning experiences in one place. No matter what kind of collection mean you choose, e.g. Evernote to trace experiences on the run, Email In to quickly trace an insight during work or directly upload of links, quick notes and resources to immediately add a valuable resource (</span><span class="s2">menu</span><span class="s1">), B&amp;P will integrate them safely for you and provide two ways of recalling them efficiently: on the one hand, a timeline (</span><span class="s3">blue</span><span class="s1">) helps you to recall your traced experiences via time based cues and on the other hand, a tag cloud (</span><span class="s4">search tab in toolbar; green</span><span class="s1">) helps to recall your traced and tagged experiences via semantic cues.</span></h3>
<h3 style="margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 15.0px Arial; color: #000000; -webkit-text-stroke: #000000"><br><span class="s1">Recalled experiences can then be narrowed down to a meaningful subset in the organizing view (</span><span class="s5">red</span><span class="s1">) with respect to a certain topic, e.g. the theme of project proposal or the description of a problem faced a work.  Afterwards, the organizing view provides the chance to make sense out of the experiences, i.e. relate them to each other by categorizing them into circles and stepwise identifying shared structures/patterns in the data. This way, experiences faced over the day are not lost, but kept safe, related to the prior knowledge, elaborated and better memorized so that they are ready to be used in practice! All the available organizations can be spotted in the </span><span class="s2">menu </span><span class="s1">of the top bar offering valuable social information, as well.</span></h3>
<h3 style="margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 15.0px Arial; color: #000000; -webkit-text-stroke: #000000"><br><span class="s1">And the best is: Once you are stuck and need help, you can invite a colleague (</span><span class="s4">sharing for co-edition - episode tab</span><span class="s1">) or a friendly community to get feedback and collaborate on your ideas …  and for sure, you can simply share your insights as well ;) (</span><span class="s4">sharing for copy - episode tab</span><span class="s1">). Respective features can be found in the toolbar (</span><span class="s4">green</span><span class="s1">), which consists of different tabs providing various additional helpful features: “Activity Stream”, “Search”, “Bit” and “Episode”</span><span class="s6">. </span><span class="s1">Just check them out and give them a try!</span></h3>
<h3 style="margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 15.0px Arial; color: #000000; -webkit-text-stroke: #000000"><br><span class="s1">If questions pop up have a look at the videos answering the Frequently Asked Questions (FAQ) below or simply drop us a message:<span class="Apple-converted-space"> </span></span></h3>
<ul class="ul1">
  <li class="li1"><span class="s7"></span><span class="s1">Pilot D Support Mailing List  <a href="mailto:learning-layers-pilotd@lists.leeds.ac.uk"><span class="s8">learning-layers-pilotd@lists.leeds.ac.uk</span></a> (Federation)<br>
</span></li>
  <li class="li1"><span class="s7"></span><span class="s1">Pilot E Support Mailing List  <a href="mailto:learning-layers-pilote@lists.leeds.ac.uk"><span class="s8">learning-layers-pilote@lists.leeds.ac.uk</span></a> (IT Group)</span></li>
</ul>
<h3 class="c18 c7" id="h.envy2ztgyuq" style="text-align:center;vertical-align:middle;"><span style="overflow: hidden; display: inline-block; margin: 0.00px 0.00px; border: 0.00px solid #000000; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px); width: 601.70px; height: 318.67px;"><img alt="" src="images/image00.png" style="width: 601.70px; height: 318.67px; margin-left: 0.00px; margin-top: 0.00px; transform: rotate(0.00rad) translateZ(0px); -webkit-transform: rotate(0.00rad) translateZ(0px);" title=""></span></h3>
<h3 style="margin: 0.0px 0.0px 0.0px 0.0px; line-height: 22.0px; font: 16.0px 'Trebuchet MS'; color: #666666; -webkit-text-stroke: #666666"><span class="s1"><b>Figure 1. General view of interface.</b></span></h3>
